/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.agendaescolar.interfaces;

import br.com.agendaescolar.classes.Responsavel;
import dao.DAOResponsavel;
import javax.swing.JOptionPane;

/**
 *
 * @author dell1
 */
public class AlterarResponsavel extends javax.swing.JInternalFrame {

    /**
     * Creates new form AlterarResponsavel
     */
    public AlterarResponsavel() {
        initComponents();
        setSize(480, 400);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelCpf = new javax.swing.JLabel();
        jTextCampoAlterar = new javax.swing.JTextField();
        jTextCPF = new javax.swing.JTextField();
        jComboBoxAletrarResp = new javax.swing.JComboBox<>();
        jButtonAlterarResp = new javax.swing.JButton();
        jButtonLimpar = new javax.swing.JButton();
        jLabelCampoAlterar = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setClosable(true);
        setTitle("Alterar Responsavel");
        getContentPane().setLayout(null);

        jLabelCpf.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabelCpf.setText("CPF");
        getContentPane().add(jLabelCpf);
        jLabelCpf.setBounds(140, 40, 71, 17);
        getContentPane().add(jTextCampoAlterar);
        jTextCampoAlterar.setBounds(160, 180, 170, 30);
        getContentPane().add(jTextCPF);
        jTextCPF.setBounds(160, 70, 170, 30);

        jComboBoxAletrarResp.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item", "Nome", "Senha", "Email" }));
        getContentPane().add(jComboBoxAletrarResp);
        jComboBoxAletrarResp.setBounds(160, 120, 161, 32);

        jButtonAlterarResp.setText("ALTERAR");
        jButtonAlterarResp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAlterarRespActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonAlterarResp);
        jButtonAlterarResp.setBounds(150, 260, 90, 23);

        jButtonLimpar.setText("LIMPAR");
        getContentPane().add(jButtonLimpar);
        jButtonLimpar.setBounds(250, 260, 90, 23);

        jLabelCampoAlterar.setText("Campo a alterar");
        getContentPane().add(jLabelCampoAlterar);
        jLabelCampoAlterar.setBounds(160, 160, 170, 14);

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\dell1\\Desktop\\lib.png")); // NOI18N
        jLabel1.setText("jLabel1");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 570, 380);
        jLabel1.getAccessibleContext().setAccessibleName("");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonAlterarRespActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAlterarRespActionPerformed
      String cpf,opcao1;
      cpf=jTextCPF.getText();
      opcao1=jTextCampoAlterar.getText();
      if(jComboBoxAletrarResp.getSelectedItem()=="Nome"){
           Responsavel obj= new Responsavel();
           obj.setCpf(cpf);
           obj.setNome(opcao1);
           DAOResponsavel objdao= new DAOResponsavel();
           objdao.alterarNome(obj);
      } else 
          if(jComboBoxAletrarResp.getSelectedItem()=="Senha"){
               Responsavel obj= new Responsavel();
               obj.setCpf(cpf);
               obj.setSenha(opcao1);
               DAOResponsavel objdao= new DAOResponsavel();
               objdao.alterarSenha(obj);
          }else
              if(jComboBoxAletrarResp.getSelectedItem()=="Email"){
                   Responsavel obj= new Responsavel();
                   obj.setCpf(cpf);
                   obj.setEmail(opcao1);
                   DAOResponsavel objdao= new DAOResponsavel();
                   objdao.alterarEmail(obj);
              } else{
                  JOptionPane.showMessageDialog(null, "Selecione um item");
              }
      
     
    }//GEN-LAST:event_jButtonAlterarRespActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAlterarResp;
    private javax.swing.JButton jButtonLimpar;
    private javax.swing.JComboBox<String> jComboBoxAletrarResp;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabelCampoAlterar;
    private javax.swing.JLabel jLabelCpf;
    private javax.swing.JTextField jTextCPF;
    private javax.swing.JTextField jTextCampoAlterar;
    // End of variables declaration//GEN-END:variables
}
