/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.agendaescolar.interfaces;
import javax.swing.JOptionPane;
import br.com.agendaescolar.classes.Aluno;
import dao.DAOAluno;

/**
 *
 * @author dell1
 */
public class AlterarAluno extends javax.swing.JInternalFrame {

    /**
     * Creates new form AlterarAluno
     */
    public AlterarAluno() {
        initComponents();
        setSize(480, 400);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelMatricula = new javax.swing.JLabel();
        jTextCampoAlterar = new javax.swing.JTextField();
        jLabelOqueAlterar = new javax.swing.JLabel();
        jTextMatricula = new javax.swing.JTextField();
        jComboBoxAletrar = new javax.swing.JComboBox<>();
        jButtonAterar = new javax.swing.JButton();
        jButtonLimpar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setClosable(true);
        setTitle("Alterar Dados Aluno");
        getContentPane().setLayout(null);

        jLabelMatricula.setText("Matricula");
        getContentPane().add(jLabelMatricula);
        jLabelMatricula.setBounds(160, 30, 79, 14);
        getContentPane().add(jTextCampoAlterar);
        jTextCampoAlterar.setBounds(160, 190, 150, 30);

        jLabelOqueAlterar.setText("O que alterar?");
        getContentPane().add(jLabelOqueAlterar);
        jLabelOqueAlterar.setBounds(160, 160, 170, 14);
        getContentPane().add(jTextMatricula);
        jTextMatricula.setBounds(160, 60, 158, 32);

        jComboBoxAletrar.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item", "Nome", "Senha" }));
        getContentPane().add(jComboBoxAletrar);
        jComboBoxAletrar.setBounds(160, 110, 170, 40);

        jButtonAterar.setText("ALTERAR");
        jButtonAterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAterarActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonAterar);
        jButtonAterar.setBounds(130, 240, 100, 30);

        jButtonLimpar.setText("LIMPAR");
        jButtonLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLimparActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonLimpar);
        jButtonLimpar.setBounds(260, 240, 90, 30);

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\dell1\\Desktop\\lib.png")); // NOI18N
        jLabel1.setText("jLabel1");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, -10, 520, 400);
        jLabel1.getAccessibleContext().setAccessibleName("");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonAterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAterarActionPerformed
      String matricula,opcao;
      matricula=jTextMatricula.getText();
      opcao=jTextCampoAlterar.getText();
      if(jComboBoxAletrar.getSelectedItem()=="Nome"){
          Aluno obj= new Aluno();
          obj.setMatricula(matricula);
          obj.setNomeAluno(opcao);
           DAOAluno objdao= new DAOAluno();
            objdao.alterarNome(obj);
            
      } else
          if(jComboBoxAletrar.getSelectedItem()=="Senha"){
              Aluno obj= new Aluno();
              obj.setMatricula(matricula);
              obj.setSenha(opcao);
              DAOAluno objdao= new DAOAluno();
              objdao.alterarSenha(obj);
             
          } else{
             JOptionPane.showMessageDialog(null, "Selecione um item");
          }
          jTextCampoAlterar.setText(null);
          jTextMatricula.setText(null);
       
    }//GEN-LAST:event_jButtonAterarActionPerformed

    private void jButtonLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLimparActionPerformed
         jTextCampoAlterar.setText(null);
          jTextMatricula.setText(null);
    }//GEN-LAST:event_jButtonLimparActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAterar;
    private javax.swing.JButton jButtonLimpar;
    private javax.swing.JComboBox<String> jComboBoxAletrar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabelMatricula;
    private javax.swing.JLabel jLabelOqueAlterar;
    private javax.swing.JTextField jTextCampoAlterar;
    private javax.swing.JTextField jTextMatricula;
    // End of variables declaration//GEN-END:variables
}
