/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.agendaescolar.interfaces;
import br.com.agendaescolar.classes.Professor;
import br.com.agendaescolar.utilitarios.ConnectionFactory;
import dao.DAOAluno;
import dao.DAOProfessor;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
public class CadastrarProfessor extends javax.swing.JInternalFrame {

    /**
     * Creates new form CadastrarProfessor
     */
    public CadastrarProfessor() {
        initComponents();
        setSize(950,500);
    }
    private void montartabelaProf(){
           String colunas[] = new String[]{"Matricula","Nome","Telefone","Email"};
           DefaultTableModel modelotabela = new DefaultTableModel(null,colunas);
           DAOProfessor  prof= new DAOProfessor();
           ArrayList<Professor> lista= prof.listarProfessor();
           
           for(Professor meuprof: lista){
                modelotabela.addRow(new Object[]{meuprof.getMatriculaProf(),meuprof.getNomeProfessor(),meuprof.getTelefone(),meuprof.getEmail()});
           }
        jTableProfessor.setModel(modelotabela);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabelNome = new javax.swing.JLabel();
        jLabelSenha = new javax.swing.JLabel();
        jLabelMatricula = new javax.swing.JLabel();
        jTextMatricula = new javax.swing.JTextField();
        jTextSenha = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabelTelefone = new javax.swing.JLabel();
        jTextTelefone = new javax.swing.JTextField();
        jLabelEmail = new javax.swing.JLabel();
        jTextEmail = new javax.swing.JTextField();
        jButtonSalvar = new javax.swing.JButton();
        jButtonCancelar = new javax.swing.JButton();
        jTextNome = new javax.swing.JTextField();
        jVoltar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableProfessor = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(204, 204, 255));
        setClosable(true);
        setIconifiable(true);
        setResizable(true);
        setTitle("Cadastrar Professor");
        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameOpened(evt);
            }
        });
        getContentPane().setLayout(null);
        getContentPane().add(jLabel1);
        jLabel1.setBounds(26, 269, 0, 0);

        jLabelNome.setText("Nome");
        getContentPane().add(jLabelNome);
        jLabelNome.setBounds(150, 20, 140, 14);

        jLabelSenha.setText("senha");
        getContentPane().add(jLabelSenha);
        jLabelSenha.setBounds(150, 80, 120, 20);

        jLabelMatricula.setText("Matricula");
        getContentPane().add(jLabelMatricula);
        jLabelMatricula.setBounds(150, 270, 80, 14);
        getContentPane().add(jTextMatricula);
        jTextMatricula.setBounds(150, 290, 300, 40);
        getContentPane().add(jTextSenha);
        jTextSenha.setBounds(150, 100, 305, 40);
        getContentPane().add(jLabel4);
        jLabel4.setBounds(39, 501, 0, 0);

        jLabelTelefone.setText("Telefone");
        getContentPane().add(jLabelTelefone);
        jLabelTelefone.setBounds(150, 150, 160, 14);

        jTextTelefone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextTelefoneActionPerformed(evt);
            }
        });
        getContentPane().add(jTextTelefone);
        jTextTelefone.setBounds(150, 170, 305, 40);

        jLabelEmail.setText("Email");
        getContentPane().add(jLabelEmail);
        jLabelEmail.setBounds(150, 210, 140, 14);

        jTextEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextEmailActionPerformed(evt);
            }
        });
        getContentPane().add(jTextEmail);
        jTextEmail.setBounds(150, 230, 305, 38);

        jButtonSalvar.setText("SALVAR");
        jButtonSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSalvarActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonSalvar);
        jButtonSalvar.setBounds(90, 340, 110, 40);

        jButtonCancelar.setText("LIMPAR");
        jButtonCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCancelarActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonCancelar);
        jButtonCancelar.setBounds(240, 340, 120, 40);
        getContentPane().add(jTextNome);
        jTextNome.setBounds(150, 40, 305, 35);

        jVoltar.setText("VOLTAR");
        getContentPane().add(jVoltar);
        jVoltar.setBounds(400, 340, 100, 40);

        jTableProfessor.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(jTableProfessor);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(480, 60, 410, 120);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(204, 0, 0));
        jLabel2.setText("Professores já cadastrados");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(490, 30, 220, 14);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/agendaescolar/imagens/fundo2.png"))); // NOI18N
        getContentPane().add(jLabel3);
        jLabel3.setBounds(-40, -150, 1090, 650);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextTelefoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextTelefoneActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextTelefoneActionPerformed

    private void jTextEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextEmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextEmailActionPerformed

    private void jButtonCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCancelarActionPerformed
       
        jTextSenha.setText(null);
        jTextTelefone.setText(null);
        jTextEmail.setText(null);
        jTextNome.setText(null);
        jTextMatricula.setText(null);
        
        
    }//GEN-LAST:event_jButtonCancelarActionPerformed

    private void jButtonSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSalvarActionPerformed
        /*variaveis para recever da tela */
        String nome,senha,telefone,email;
        String matricula;
        nome=jTextNome.getText();
        senha=jTextSenha.getText();
        telefone=jTextTelefone.getText();
        email=jTextEmail.getText();
        matricula=jTextMatricula.getText();
                
        
        /* criando o objeto Professor*/
        Professor objProfessor= new Professor();
        objProfessor.setNomeProfessor(nome);
        objProfessor.setSenhaProfessor(senha);
        objProfessor.setTelefone(telefone);
        objProfessor.setEmail(email);
        objProfessor.setMatriculaProf(matricula);
        DAOProfessor objdao= new DAOProfessor();
        objdao.salvarProfessor(objProfessor);
        montartabelaProf();
           jTextNome.setText(null);
            jTextSenha.setText(null);
            jTextTelefone.setText(null);
            jTextEmail.setText(null);
            jTextMatricula.setText(null);
          
       
        
    }//GEN-LAST:event_jButtonSalvarActionPerformed

    private void formInternalFrameOpened(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameOpened
       montartabelaProf();
    }//GEN-LAST:event_formInternalFrameOpened


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonCancelar;
    private javax.swing.JButton jButtonSalvar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabelEmail;
    private javax.swing.JLabel jLabelMatricula;
    private javax.swing.JLabel jLabelNome;
    private javax.swing.JLabel jLabelSenha;
    private javax.swing.JLabel jLabelTelefone;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableProfessor;
    private javax.swing.JTextField jTextEmail;
    private javax.swing.JTextField jTextMatricula;
    private javax.swing.JTextField jTextNome;
    private javax.swing.JTextField jTextSenha;
    private javax.swing.JTextField jTextTelefone;
    private javax.swing.JButton jVoltar;
    // End of variables declaration//GEN-END:variables
}
