/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.agendaescolar.interfaces;

import br.com.agendaescolar.classes.Professor;
import br.com.agendaescolar.classes.Turma;
import dao.DAOProfessor;
import dao.DAOTurma;
import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author dell1
 */
public class CadastrarTurma extends javax.swing.JInternalFrame {

    /**
     * Creates new form CadastrarTurma
     */
    public CadastrarTurma() {
        initComponents();
        setSize(700, 500);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    private void montarTabela(){
      //  DAOAluno objaluno= new DAOAluno();
        //  int idA=objaluno.idAluno;
     // TODO add your handling code here:
        //Dados para a montagem das Colunas
        String colunas[] = new String[]{"Id","Ano","Turno"};
        //Criacao do objeto que define o modelo da Tabela
        //Passamos null no primeiro argumento, pois as linhas serão definidas
        //Dentro do foreach. Ele recebe como argumento um vetor de Objetos
        DefaultTableModel modelotabela = new DefaultTableModel(null,colunas);
        
        //Criação do objeto DAOAluno para recuperar os dados dos alunos
        //que estão na Tabela Aluno
        DAOTurma  turma= new DAOTurma();
        //Chamada do método que retorna todos os alunos cadastrados
        //na tabela Aluno
        ArrayList<Turma> Lista = turma.retornarTurma();
        //ForEach que pega cada objeto aluno da ListaA e atribui
        //ao objeto Aluno a
        for(Turma a : Lista){
            //Nesta linha nos adicionamos as linhas na tabela
            //Montamos aqui um Vetor de Objetos
            modelotabela.addRow(new Object[]{a.getIdTurma(), a.getNomeTurma(),a.getTurno()});
             
        }
     
        
     jTableTurma.setModel(modelotabela);
              
        
    }   
    
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelAno = new javax.swing.JLabel();
        jLabelTurno = new javax.swing.JLabel();
        jTextAno = new javax.swing.JTextField();
        jButtonSalvar = new javax.swing.JButton();
        jComboBoxTurno = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableTurma = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setClosable(true);
        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameOpened(evt);
            }
        });
        getContentPane().setLayout(null);

        jLabelAno.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabelAno.setText("Ano");
        getContentPane().add(jLabelAno);
        jLabelAno.setBounds(130, 100, 90, 30);

        jLabelTurno.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabelTurno.setText("Turno");
        getContentPane().add(jLabelTurno);
        jLabelTurno.setBounds(130, 180, 90, 17);
        getContentPane().add(jTextAno);
        jTextAno.setBounds(130, 130, 180, 40);

        jButtonSalvar.setText("SALVAR");
        jButtonSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSalvarActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonSalvar);
        jButtonSalvar.setBounds(130, 280, 160, 40);

        jComboBoxTurno.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item", "Matutino", "Vespertino" }));
        getContentPane().add(jComboBoxTurno);
        jComboBoxTurno.setBounds(130, 210, 180, 40);

        jTableTurma.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(jTableTurma);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(332, 51, 302, 102);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 0, 0));
        jLabel1.setText("Turmas Cadastradas");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(332, 30, 145, 14);

        jLabel2.setIcon(new javax.swing.ImageIcon("C:\\Users\\dell1\\Desktop\\fundo2.png")); // NOI18N
        getContentPane().add(jLabel2);
        jLabel2.setBounds(-50, -190, 840, 660);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formInternalFrameOpened(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameOpened
    montarTabela();
      
    }//GEN-LAST:event_formInternalFrameOpened

    private void jButtonSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSalvarActionPerformed
           
 
            String ano;
             String item;
             String nomeProfessor;
             ano=jTextAno.getText();
             item=jComboBoxTurno.getSelectedItem().toString();
             
             Turma objt= new Turma();
           
             objt.setNomeTurma(ano);
             objt.setTurno(item);
             DAOTurma turma= new DAOTurma();
            turma.salvarTurma(objt);
             montarTabela();
    }//GEN-LAST:event_jButtonSalvarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonSalvar;
    private javax.swing.JComboBox<String> jComboBoxTurno;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabelAno;
    private javax.swing.JLabel jLabelTurno;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableTurma;
    private javax.swing.JTextField jTextAno;
    // End of variables declaration//GEN-END:variables
}
