/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.agendaescolar.interfaces;
import br.com.agendaescolar.classes.Aluno;
import br.com.agendaescolar.utilitarios.ConnectionFactory;
import dao.DAOAluno;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author dell1
 */
public class CadastrarA extends javax.swing.JInternalFrame {

    /**
     * Creates new form CadastrarA
     */
    public CadastrarA() {
        initComponents();
        setSize(950, 500);
    }
      private void montartabelaAluno(){
           String colunas[] = new String[]{"Id","Nome","matricula"};
           DefaultTableModel modelotabela = new DefaultTableModel(null,colunas);
           DAOAluno ALUNO= new DAOAluno();
           ArrayList<Aluno> lista= ALUNO.listarAluno();
           
           for(Aluno meualuno: lista){
                modelotabela.addRow(new Object[]{meualuno.getCod(), meualuno.getNomeAluno(),meualuno.getMatricula()});
           }
        jTableaAlunos.setModel(modelotabela);
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelNome = new javax.swing.JLabel();
        jLabelSenha = new javax.swing.JLabel();
        jTextNome = new javax.swing.JTextField();
        jTextSenha = new javax.swing.JTextField();
        jButtonSalvar = new javax.swing.JButton();
        jButtonCancelar = new javax.swing.JButton();
        jLabelMatricula = new javax.swing.JLabel();
        jTextMatricula = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableaAlunos = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jButtonExcluir = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jTextIdAluno = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setClosable(true);
        setForeground(java.awt.Color.gray);
        setIconifiable(true);
        setTitle("Cadastro de Aluno");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameOpened(evt);
            }
        });
        getContentPane().setLayout(null);

        jLabelNome.setText("Nome");
        getContentPane().add(jLabelNome);
        jLabelNome.setBounds(150, 20, 160, 32);

        jLabelSenha.setText("Senha");
        getContentPane().add(jLabelSenha);
        jLabelSenha.setBounds(150, 80, 130, 32);

        jTextNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextNomeActionPerformed(evt);
            }
        });
        getContentPane().add(jTextNome);
        jTextNome.setBounds(150, 50, 197, 32);
        getContentPane().add(jTextSenha);
        jTextSenha.setBounds(150, 110, 197, 33);

        jButtonSalvar.setText("SALVAR");
        jButtonSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSalvarActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonSalvar);
        jButtonSalvar.setBounds(130, 330, 90, 40);

        jButtonCancelar.setText("LIMPAR");
        jButtonCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCancelarActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonCancelar);
        jButtonCancelar.setBounds(260, 330, 90, 40);

        jLabelMatricula.setText("Matricula");
        getContentPane().add(jLabelMatricula);
        jLabelMatricula.setBounds(150, 150, 90, 14);
        getContentPane().add(jTextMatricula);
        jTextMatricula.setBounds(150, 180, 200, 32);

        jTableaAlunos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jTableaAlunos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableaAlunosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTableaAlunos);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(450, 90, 410, 130);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(204, 0, 0));
        jLabel1.setText("Alunos já cadastrados ");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(460, 60, 230, 17);

        jButtonExcluir.setText("EXCLUIR ");
        jButtonExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonExcluirActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonExcluir);
        jButtonExcluir.setBounds(380, 330, 110, 40);

        jLabel2.setFont(new java.awt.Font("Tahoma", 3, 11)); // NOI18N
        jLabel2.setText("Selecione a linha a ser excluída:");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(460, 230, 190, 14);

        jTextIdAluno.setEnabled(false);
        jTextIdAluno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextIdAlunoActionPerformed(evt);
            }
        });
        getContentPane().add(jTextIdAluno);
        jTextIdAluno.setBounds(460, 250, 40, 20);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/agendaescolar/imagens/fundo2.png"))); // NOI18N
        getContentPane().add(jLabel3);
        jLabel3.setBounds(-110, -170, 1230, 760);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextNomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextNomeActionPerformed

    private void jButtonSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSalvarActionPerformed
          PreparedStatement stmt;
          String comandoSql;
          String nome,senha,matricula;
          
          nome= jTextNome.getText();
          senha=jTextSenha.getText();
          matricula=jTextMatricula.getText();
          /*Criar um objeto*/
          Aluno objAluno1= new Aluno();
          objAluno1.setNomeAluno(nome);
          objAluno1.setSenha(senha);
          objAluno1.setMatricula(matricula);
          /**/
          DAOAluno objdao = new DAOAluno();
        try {
            objdao.salvar(objAluno1);
              montartabelaAluno();
            jTextNome.setText(null);
            jTextSenha.setText(null);
            jTextMatricula.setText(null);
            
           
        } catch (SQLException ex) {
            Logger.getLogger(CadastrarA.class.getName()).log(Level.SEVERE, null, ex);
        }
          
          
    }//GEN-LAST:event_jButtonSalvarActionPerformed

    private void jButtonCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCancelarActionPerformed
        jTextNome.setText(null);
        jTextSenha.setText(null);
        jTextMatricula.setText(null);
    }//GEN-LAST:event_jButtonCancelarActionPerformed

    private void formInternalFrameOpened(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameOpened
        //Torna o campo que guarda o ID do aluno, invisível
        jTextIdAluno.setVisible(false);
        montartabelaAluno();
    }//GEN-LAST:event_formInternalFrameOpened

    private void jTableaAlunosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableaAlunosMouseClicked
        // TODO add your handling code here:
        int linha=0,idAluno=0;
        if (evt.getClickCount() == 1){
            linha = jTableaAlunos.getSelectedRow();
            idAluno = (int) jTableaAlunos.getValueAt(linha, 0);
            String op= Integer.toString(idAluno);
            jTextIdAluno.setText(op); 
            //JOptionPane.showMessageDialog(null, campo);
        }
        
    }//GEN-LAST:event_jTableaAlunosMouseClicked

    private void jButtonExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonExcluirActionPerformed
     
      int idaluno;
     String valorid;
     boolean resposta;
     valorid=jTextIdAluno.getText();
     if(valorid.isEmpty()){
         JOptionPane.showMessageDialog(null, "Selecione uma linha da tabela");
     }
     else {
         idaluno=  Integer.parseInt(valorid);
         DAOAluno objdao= new DAOAluno();
         resposta=objdao.apagar(idaluno);
         if(resposta==true){
             JOptionPane.showMessageDialog(null, "Exclusão realizada com sucessor");
             montartabelaAluno();
         }
         else{
             JOptionPane.showMessageDialog(null, "Seu aluno esta vinculado em outras tabelas");
         }
     }
    
     
     
    }//GEN-LAST:event_jButtonExcluirActionPerformed

    private void jTextIdAlunoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextIdAlunoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextIdAlunoActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonCancelar;
    private javax.swing.JButton jButtonExcluir;
    private javax.swing.JButton jButtonSalvar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabelMatricula;
    private javax.swing.JLabel jLabelNome;
    private javax.swing.JLabel jLabelSenha;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableaAlunos;
    private javax.swing.JTextField jTextIdAluno;
    private javax.swing.JTextField jTextMatricula;
    private javax.swing.JTextField jTextNome;
    private javax.swing.JTextField jTextSenha;
    // End of variables declaration//GEN-END:variables
}
