
package br.com.agendaescolar.interfaces;

import br.com.agendaescolar.classes.Responsavel;
import dao.DAOResponsavel;

import java.sql.PreparedStatement;
import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;
public class CadastrarResponsavel extends javax.swing.JInternalFrame {

   

    public CadastrarResponsavel() {
        initComponents();
        setSize(950,500);
    }
    private void montartabelaresp(){
           String colunas[] = new String[]{"CPF","Nome","Email"};
           DefaultTableModel modelotabela = new DefaultTableModel(null,colunas);
           DAOResponsavel resp= new DAOResponsavel();
           ArrayList<Responsavel> lista= resp.listarResponsavel();
           
           for( Responsavel meuRespo: lista){
                modelotabela.addRow(new Object[]{meuRespo.getCpf(),meuRespo.getNome(),meuRespo.getEmail()});
           }
        jTableResponsavel.setModel(modelotabela);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jcpfResponsavel = new javax.swing.JLabel();
        jTextCpf = new javax.swing.JTextField();
        jNomeResponsavel = new javax.swing.JLabel();
        jSenhaResponsavel = new javax.swing.JLabel();
        jEmailResponsavel = new javax.swing.JLabel();
        jTextNome = new javax.swing.JTextField();
        jTextSenha = new javax.swing.JTextField();
        jTextEmail = new javax.swing.JTextField();
        jButtonSalvar = new javax.swing.JButton();
        jButtonCancelar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableResponsavel = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();

        setClosable(true);
        setIconifiable(true);
        setResizable(true);
        setTitle("Cadastro Responsavel");
        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameOpened(evt);
            }
        });
        getContentPane().setLayout(null);

        jcpfResponsavel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jcpfResponsavel.setText("CPF");
        getContentPane().add(jcpfResponsavel);
        jcpfResponsavel.setBounds(130, 180, 110, 25);

        jTextCpf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextCpfActionPerformed(evt);
            }
        });
        getContentPane().add(jTextCpf);
        jTextCpf.setBounds(130, 200, 230, 34);

        jNomeResponsavel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jNomeResponsavel.setText("Nome");
        getContentPane().add(jNomeResponsavel);
        jNomeResponsavel.setBounds(130, 130, 110, 17);

        jSenhaResponsavel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jSenhaResponsavel.setText("Senha");
        getContentPane().add(jSenhaResponsavel);
        jSenhaResponsavel.setBounds(130, 240, 59, 17);

        jEmailResponsavel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jEmailResponsavel.setText("Email");
        getContentPane().add(jEmailResponsavel);
        jEmailResponsavel.setBounds(130, 300, 90, 17);

        jTextNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextNomeActionPerformed(evt);
            }
        });
        getContentPane().add(jTextNome);
        jTextNome.setBounds(130, 150, 230, 32);
        getContentPane().add(jTextSenha);
        jTextSenha.setBounds(130, 260, 230, 32);

        jTextEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextEmailActionPerformed(evt);
            }
        });
        getContentPane().add(jTextEmail);
        jTextEmail.setBounds(130, 320, 230, 32);

        jButtonSalvar.setText("SALVAR");
        jButtonSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSalvarActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonSalvar);
        jButtonSalvar.setBounds(140, 400, 110, 40);

        jButtonCancelar.setText("LIMPAR");
        jButtonCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCancelarActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonCancelar);
        jButtonCancelar.setBounds(270, 400, 110, 40);

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\dell1\\Desktop\\projeto\\trab Java\\mulher.png")); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(160, 10, 130, 117);

        jLabel2.setIcon(new javax.swing.ImageIcon("C:\\Users\\dell1\\Desktop\\projeto\\trab Java\\homem.png")); // NOI18N
        getContentPane().add(jLabel2);
        jLabel2.setBounds(290, 0, 128, 128);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(204, 0, 0));
        jLabel4.setText("Responsaveis já cadastrados ");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(480, 50, 250, 17);

        jTableResponsavel.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(jTableResponsavel);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(480, 80, 380, 120);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/agendaescolar/imagens/fundo2.png"))); // NOI18N
        getContentPane().add(jLabel3);
        jLabel3.setBounds(-20, -170, 990, 660);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextCpfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextCpfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextCpfActionPerformed

    private void jTextNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextNomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextNomeActionPerformed

    private void jTextEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextEmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextEmailActionPerformed

    private void jButtonSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSalvarActionPerformed

   /*  Criar as variaveis para receber as caixas de texto*/
    String nomeResponsavel,cpfResponsavel;
    String senhaResponsavel,email,telefone;  
    cpfResponsavel=jTextCpf.getText();
    nomeResponsavel=jTextNome.getText();
    senhaResponsavel=jTextSenha.getText();
    email=jTextEmail.getText();
  
   //Criou um objeto para Responsavel
   Responsavel objResponsavel= new Responsavel();
   objResponsavel.setCpf(cpfResponsavel);
   objResponsavel.setNome(nomeResponsavel);
   objResponsavel.setSenha(senhaResponsavel);
   objResponsavel.setEmail(email);
    
    DAOResponsavel objR= new DAOResponsavel();
    objR.salvarResponsavel(objResponsavel);
    montartabelaresp();
    jTextCpf.setText(null);
    jTextEmail.setText(null);
    jTextSenha.setText(null);
    jTextNome.setText(null);  
        
        
        
    }//GEN-LAST:event_jButtonSalvarActionPerformed

    private void jButtonCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCancelarActionPerformed
       jTextCpf.setText(null);
       jTextNome.setText(null);
       jTextSenha.setText(null);
       jTextEmail.setText(null);
        
    }//GEN-LAST:event_jButtonCancelarActionPerformed

    private void formInternalFrameOpened(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameOpened
      montartabelaresp();
    }//GEN-LAST:event_formInternalFrameOpened


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonCancelar;
    private javax.swing.JButton jButtonSalvar;
    private javax.swing.JLabel jEmailResponsavel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jNomeResponsavel;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel jSenhaResponsavel;
    private javax.swing.JTable jTableResponsavel;
    private javax.swing.JTextField jTextCpf;
    private javax.swing.JTextField jTextEmail;
    private javax.swing.JTextField jTextNome;
    private javax.swing.JTextField jTextSenha;
    private javax.swing.JLabel jcpfResponsavel;
    // End of variables declaration//GEN-END:variables
}
