/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.agendaescolar.interfaces;

import br.com.agendaescolar.classes.Aluno;
import br.com.agendaescolar.classes.Observacao;
import br.com.agendaescolar.classes.Turma;
import dao.DAOObservacao;
import dao.DAOProfessor;
import dao.DAOResponsavel;
import dao.DAOTurma;
import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author dell1
 */
public class ProfessorObservação extends javax.swing.JInternalFrame {

    /**
     * Creates new form ProfessorObservação
     */
    public ProfessorObservação() {
        initComponents();
        setSize(900, 600);
    }
    
   private void montarObservacao(){
        String colunas[] = new String[]{"Descrição","Professor","Aluno"};
        DefaultTableModel modelotabela = new DefaultTableModel(null,colunas);
        DAOObservacao obj= new DAOObservacao();
        DAOProfessor objr= new DAOProfessor();
       ArrayList<Observacao> ListaA = obj.retornarOb();
        for( Observacao a : ListaA){
            String nomeAluno,nomeProf;
            
             nomeAluno =obj.retornaNome(a.getIdAluno());
             nomeProf=objr.retornaNome(a.getIdProfessor());
          modelotabela.addRow(new Object[]{a.getDescricao(),nomeProf,nomeAluno});    
        }
     
       jTableObservacao.setModel(modelotabela);
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jComboBoxT23 = new javax.swing.JComboBox<>();
        jLabelTurma = new javax.swing.JLabel();
        jComboBoxNomeAluno = new javax.swing.JComboBox<>();
        jLabelAluno = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableObservacao = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextDescricao = new javax.swing.JTextArea();
        jButton1 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();

        setClosable(true);
        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameOpened(evt);
            }
        });
        getContentPane().setLayout(null);

        jComboBoxT23.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxT23ActionPerformed(evt);
            }
        });
        getContentPane().add(jComboBoxT23);
        jComboBoxT23.setBounds(70, 69, 149, 37);

        jLabelTurma.setText("Selecionar Turma");
        getContentPane().add(jLabelTurma);
        jLabelTurma.setBounds(70, 44, 82, 14);

        getContentPane().add(jComboBoxNomeAluno);
        jComboBoxNomeAluno.setBounds(70, 149, 149, 44);

        jLabelAluno.setText("Nome do aluno ");
        getContentPane().add(jLabelAluno);
        jLabelAluno.setBounds(70, 124, 74, 14);

        jTableObservacao.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(jTableObservacao);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(328, 69, 423, 95);

        jLabel1.setText("Observações");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(338, 44, 63, 14);

        jTextDescricao.setColumns(20);
        jTextDescricao.setRows(5);
        jScrollPane2.setViewportView(jTextDescricao);

        getContentPane().add(jScrollPane2);
        jScrollPane2.setBounds(70, 211, 250, 120);

        jButton1.setText("SALVAR");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(70, 349, 121, 34);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/agendaescolar/imagens/fundo2.png"))); // NOI18N
        getContentPane().add(jLabel3);
        jLabel3.setBounds(-36, -80, 1020, 670);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       String opcaoturma;
       String opcaoAluno;
       String descricao;
       DAOProfessor prp= new DAOProfessor();
        int id=prp.idProfessor; 
    
       opcaoAluno= jComboBoxNomeAluno.getSelectedItem().toString();
         int idaluno=Integer.parseInt(opcaoAluno);
       descricao=jTextDescricao.getText();
       Observacao obj1= new Observacao();
       obj1.setIdProfessor(id);
       obj1.setIdAluno(idaluno);
       obj1.setDescricao(descricao);
       DAOObservacao OBJDAO= new DAOObservacao();
       OBJDAO.salvarObservacao(obj1);
       montarObservacao();
       
    }//GEN-LAST:event_jButton1ActionPerformed

    private void formInternalFrameOpened(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameOpened
  
         DAOTurma objt= new DAOTurma();
         DAOProfessor prof= new DAOProfessor();
         int idp= prof.idProfessor;
       ArrayList<Turma> lista=objt.turmare(idp);
       for (Turma minhaTurma: lista){
          
            jComboBoxT23.addItem(minhaTurma.retornaId());
        }
       montarObservacao();
    }//GEN-LAST:event_formInternalFrameOpened

    private void jComboBoxT23ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxT23ActionPerformed
      String opcao= jComboBoxT23.getSelectedItem().toString();
        int op=Integer.parseInt(opcao);
        DAOTurma obj1= new DAOTurma();
        ArrayList<Aluno> lista=obj1.retornaridaluno(op);
        jComboBoxNomeAluno.removeAllItems();
        for ( Aluno meu:lista){
            
            jComboBoxNomeAluno.addItem(meu.retornaid());
        }
 
    }//GEN-LAST:event_jComboBoxT23ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox<String> jComboBoxNomeAluno;
    private javax.swing.JComboBox<String> jComboBoxT23;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabelAluno;
    private javax.swing.JLabel jLabelTurma;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTableObservacao;
    private javax.swing.JTextArea jTextDescricao;
    // End of variables declaration//GEN-END:variables
}
