/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.agendaescolar.interfaces;

import br.com.agendaescolar.classes.Aluno;
import br.com.agendaescolar.classes.Responsavel;
import br.com.agendaescolar.utilitarios.ModeloTabela;
import dao.DAOAluno;
import dao.DAOResponsavel;
import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author dell1
 */
public class Relacionar extends javax.swing.JInternalFrame {

    /**
     * Creates new form Relacionar
     */
    public Relacionar() {
        initComponents();
        setSize(800, 500);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jResponsavel = new javax.swing.JLabel();
        jAluno = new javax.swing.JLabel();
        jComboBoxResp = new javax.swing.JComboBox<>();
        jComboBoxAluno = new javax.swing.JComboBox<>();
        jButtonVincular = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableAlunoResp = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setClosable(true);
        setIconifiable(true);
        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameOpened(evt);
            }
        });
        getContentPane().setLayout(null);

        jResponsavel.setText("Responsavel");
        getContentPane().add(jResponsavel);
        jResponsavel.setBounds(140, 50, 90, 14);

        jAluno.setText("Aluno");
        getContentPane().add(jAluno);
        jAluno.setBounds(140, 140, 100, 14);

        jComboBoxResp.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        getContentPane().add(jComboBoxResp);
        jComboBoxResp.setBounds(140, 80, 190, 30);

        jComboBoxAluno.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        getContentPane().add(jComboBoxAluno);
        jComboBoxAluno.setBounds(140, 170, 180, 30);

        jButtonVincular.setText("VINCULAR");
        jButtonVincular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonVincularActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonVincular);
        jButtonVincular.setBounds(140, 230, 120, 30);

        jTableAlunoResp.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(jTableAlunoResp);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(380, 80, 380, 90);

        jLabel2.setText("Alunos e Responsavel");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(380, 50, 160, 14);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/agendaescolar/imagens/fundo2.png"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(-30, -210, 1020, 710);

        pack();
    }// </editor-fold>//GEN-END:initComponents
  private void montartabelaAluno(){
      
           String colunas[] = new String[]{"Id Responsael"," id Aluno"};
           DefaultTableModel modelotabela = new DefaultTableModel(null,colunas);
           DAOResponsavel obj= new DAOResponsavel();
           DAOAluno OBJA= new DAOAluno();
           ArrayList<Responsavel> lista=obj.retornarRelacao();
           for ( Responsavel meuluno: lista){
          String nome= obj.retornarNome(meuluno.getIdresponsavel());
          String nomealuno= OBJA.retornaNome(meuluno.getIdAluno());
              modelotabela.addRow(new Object[]{nome,nomealuno});
               
           }
        jTableAlunoResp.setModel(modelotabela);
    }
    
    
    private void formInternalFrameOpened(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameOpened
        
         
            DAOAluno objdaoA= new DAOAluno();
            
            ArrayList<Aluno> lista = objdaoA.listarAluno();
            jComboBoxAluno.removeAllItems();
            for (Aluno meualuno : lista) {
                jComboBoxAluno.addItem(meualuno.toString());    
            }
            DAOResponsavel objdaoR =new DAOResponsavel();
            ArrayList<Responsavel> listaR= objdaoR.listarResponsavel();
            jComboBoxResp.removeAllItems();
            for(Responsavel resp: listaR){
                jComboBoxResp.addItem(resp.toString());
            }
           montartabelaAluno();
    }//GEN-LAST:event_formInternalFrameOpened

    private void jButtonVincularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonVincularActionPerformed
         String nomeResponsavel, nomeAluno;
         nomeResponsavel=jComboBoxResp.getSelectedItem().toString();
         nomeAluno=jComboBoxAluno.getSelectedItem().toString();
         DAOResponsavel objdaor= new DAOResponsavel();
         objdaor.salvarAlunos(nomeAluno, nomeResponsavel);
         montartabelaAluno();
    }//GEN-LAST:event_jButtonVincularActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jAluno;
    private javax.swing.JButton jButtonVincular;
    private javax.swing.JComboBox<String> jComboBoxAluno;
    private javax.swing.JComboBox<String> jComboBoxResp;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jResponsavel;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableAlunoResp;
    // End of variables declaration//GEN-END:variables
}
