/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.agendaescolar.interfaces;

import br.com.agendaescolar.classes.Aluno;
import br.com.agendaescolar.classes.Atividade;
import br.com.agendaescolar.classes.Turma;
import dao.DAOAluno;
import dao.DAOAtividade;
import dao.DAOTurma;
import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author dell1
 */
public class RelacionarTurmaAluno extends javax.swing.JInternalFrame {

    /**
     * Creates new form RelacionarProfessor
     */
    public RelacionarTurmaAluno() {
        initComponents();
        setSize(800, 500);
    }
    
     private void montartabelaTurmaeAluno(){
           String colunas[] = new String[]{"Codigo de Turma ","Codigo de Aluno"};
           DefaultTableModel modelotabela = new DefaultTableModel(null,colunas);
         
          DAOTurma obj= new DAOTurma();
           ArrayList<Turma> lista=obj.retornaTurmaeAluno();
           
           for( Turma p: lista){
                modelotabela.addRow(new Object[]{p.getIdTurma(),p.getIdAluno()});
           }
        jTableRelação.setModel(modelotabela);
    }
    
    
    
    private void montarTabela(){
      //  DAOAluno objaluno= new DAOAluno();
        //  int idA=objaluno.idAluno;
     // TODO add your handling code here:
        //Dados para a montagem das Colunas
        String colunas[] = new String[]{"Id","Ano","Turno"};
        //Criacao do objeto que define o modelo da Tabela
        //Passamos null no primeiro argumento, pois as linhas serão definidas
        //Dentro do foreach. Ele recebe como argumento um vetor de Objetos
        DefaultTableModel modelotabela = new DefaultTableModel(null,colunas);
        
        //Criação do objeto DAOAluno para recuperar os dados dos alunos
        //que estão na Tabela Aluno
        DAOTurma  turma= new DAOTurma();
        //Chamada do método que retorna todos os alunos cadastrados
        //na tabela Aluno
        ArrayList<Turma> Lista = turma.retornarTurma();
        //ForEach que pega cada objeto aluno da ListaA e atribui
        //ao objeto Aluno a
        for(Turma a : Lista){
            //Nesta linha nos adicionamos as linhas na tabela
            //Montamos aqui um Vetor de Objetos
            modelotabela.addRow(new Object[]{a.getIdTurma(), a.getNomeTurma(),a.getTurno()});
             
        }
     
        
     jTableTurma.setModel(modelotabela);
              
        
    }
    
    private void montartabelaAluno(){
           String colunas[] = new String[]{"Id","Nome","matricula"};
           DefaultTableModel modelotabela = new DefaultTableModel(null,colunas);
           DAOAluno ALUNO= new DAOAluno();
           ArrayList<Aluno> lista= ALUNO.listarAluno();
           
           for(Aluno meualuno: lista){
                modelotabela.addRow(new Object[]{meualuno.getCod(), meualuno.getNomeAluno(),meualuno.getMatricula()});
           }
        jTableAlunos.setModel(modelotabela);
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabelAluno = new javax.swing.JLabel();
        jComboBoxAluno = new javax.swing.JComboBox<>();
        jLabelProfessor = new javax.swing.JLabel();
        jComboBoxTurma = new javax.swing.JComboBox<>();
        jButtonSalvar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableTurma = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTableAlunos = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTableRelação = new javax.swing.JTable();
        jLabel4 = new javax.swing.JLabel();

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/agendaescolar/imagens/fundo2.png"))); // NOI18N

        setClosable(true);
        setIconifiable(true);
        setTitle("Relacionar Aluno e Turma");
        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameOpened(evt);
            }
        });
        getContentPane().setLayout(null);

        jLabelAluno.setText("Aluno");
        getContentPane().add(jLabelAluno);
        jLabelAluno.setBounds(160, 120, 120, 14);

        jComboBoxAluno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxAlunoActionPerformed(evt);
            }
        });
        getContentPane().add(jComboBoxAluno);
        jComboBoxAluno.setBounds(160, 150, 150, 40);

        jLabelProfessor.setText("Turma");
        getContentPane().add(jLabelProfessor);
        jLabelProfessor.setBounds(160, 40, 120, 14);

        getContentPane().add(jComboBoxTurma);
        jComboBoxTurma.setBounds(160, 60, 150, 40);

        jButtonSalvar.setText("SALVAR");
        jButtonSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSalvarActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonSalvar);
        jButtonSalvar.setBounds(160, 270, 130, 40);

        jTableTurma.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(jTableTurma);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(380, 50, 390, 90);

        jLabel2.setText("Id de Turmas já cadastradas ");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(380, 30, 240, 14);

        jTableAlunos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane2.setViewportView(jTableAlunos);

        getContentPane().add(jScrollPane2);
        jScrollPane2.setBounds(380, 180, 390, 90);

        jLabel3.setText("Id de alunos já cadastrados ");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(390, 160, 160, 14);

        jTableRelação.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane3.setViewportView(jTableRelação);

        getContentPane().add(jScrollPane3);
        jScrollPane3.setBounds(380, 310, 390, 90);

        jLabel4.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        jLabel4.setText("Relacionamento Turma e Aluno");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(380, 280, 260, 17);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jComboBoxAlunoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxAlunoActionPerformed
       
    }//GEN-LAST:event_jComboBoxAlunoActionPerformed

    private void formInternalFrameOpened(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameOpened
         DAOTurma objTurma = new DAOTurma();
        ArrayList<Turma> lista1= objTurma.retornarTurma();
        for (Turma minhaTurma: lista1){
            jComboBoxTurma.addItem(minhaTurma.retornaId());
        }
        
        DAOAluno objdaoA= new DAOAluno();
            
            ArrayList<Aluno> lista = objdaoA.listarAluno();
            jComboBoxAluno.removeAllItems();
            for (Aluno meualuno : lista) {
                jComboBoxAluno.addItem(meualuno.retornaid());    
            }
        montarTabela();
        montartabelaAluno();
        montartabelaTurmaeAluno();
    }//GEN-LAST:event_formInternalFrameOpened

    private void jButtonSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSalvarActionPerformed
        String opcaoAluno;
        String opcaoTurma;
        opcaoAluno=jComboBoxAluno.getSelectedItem().toString();
        opcaoTurma=jComboBoxTurma.getSelectedItem().toString();
        DAOTurma objt= new DAOTurma();
        objt.salvarTurmaAluno(opcaoTurma, opcaoAluno);
        montartabelaTurmaeAluno();
        
    }//GEN-LAST:event_jButtonSalvarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonSalvar;
    private javax.swing.JComboBox<String> jComboBoxAluno;
    private javax.swing.JComboBox<String> jComboBoxTurma;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabelAluno;
    private javax.swing.JLabel jLabelProfessor;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable jTableAlunos;
    private javax.swing.JTable jTableRelação;
    private javax.swing.JTable jTableTurma;
    // End of variables declaration//GEN-END:variables
}
