/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.agendaescolar.interfaces;

import br.com.agendaescolar.classes.Aluno;
import br.com.agendaescolar.classes.Atividade;
import br.com.agendaescolar.classes.Observacao;
import dao.DAOAluno;
import dao.DAOAtividade;
import dao.DAOObservacao;
import dao.DAOProfessor;
import dao.DAOResponsavel;
import dao.DAOTurma;
import java.util.ArrayList;
import javax.swing.JComboBox;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author dell1
 */
public class ResponsavelAgenda extends javax.swing.JInternalFrame {
  public int idAluno; 
  public int idturma;
    /**
     * Creates new form ResponsavelAgenda
     */
    public ResponsavelAgenda() {
        initComponents();
        setSize(700, 500);
        if(jComboBoxAluno.getItemCount() > 0){
            jComboBoxAluno = new JComboBox<>();
        }
    }
    private void montarObservacao(){
        String colunas[] = new String[]{"Descrição","Professor","Aluno"};
        DefaultTableModel modelotabela = new DefaultTableModel(null,colunas);
        DAOObservacao obj= new DAOObservacao();
        DAOProfessor objr= new DAOProfessor();
       ArrayList<Observacao> ListaA = obj.retornarObAluno(idAluno);
        for( Observacao a : ListaA){
            String nomeAluno,nomeProf;
            
             nomeAluno =obj.retornaNome(a.getIdAluno());
             nomeProf=objr.retornaNome(a.getIdProfessor());
          modelotabela.addRow(new Object[]{a.getDescricao(),nomeProf,nomeAluno});    
        }
     
       jTable1.setModel(modelotabela);
    }
     private void montarAtividade(){
        DAOAluno objaluno= new DAOAluno();
          int idA= idturma;
        String colunas[] = new String[]{"Atividade","Disciplina","Nome Professor","Turma"};
        DefaultTableModel modelotabela = new DefaultTableModel(null,colunas);
        DAOAtividade daoatividade = new DAOAtividade();
       ArrayList<Atividade> ListaA = daoatividade.listarAtividade(idA, "ALUNO");
        for(Atividade a : ListaA){
              DAOProfessor objr= new DAOProfessor();
            String nomeProf=objr.retornaNome(a.getIdProf());
            modelotabela.addRow(new Object[]{a.getDescricaoAtividade(), a.getDisciplina(),nomeProf,a.getIdTurma()});              
        }
     
       jTableAtividade.setModel(modelotabela);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelAluno = new javax.swing.JLabel();
        jComboBoxAluno = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableAtividade = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setClosable(true);
        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameOpened(evt);
            }
        });
        getContentPane().setLayout(null);

        jLabelAluno.setText("Selecionar Aluno");
        getContentPane().add(jLabelAluno);
        jLabelAluno.setBounds(46, 39, 91, 14);

        jComboBoxAluno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxAlunoActionPerformed(evt);
            }
        });
        getContentPane().add(jComboBoxAluno);
        jComboBoxAluno.setBounds(46, 71, 299, 34);

        jTableAtividade.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(jTableAtividade);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(46, 144, 315, 73);

        jLabel1.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        jLabel1.setText("Atividade passada pelo professor");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(46, 116, 260, 17);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane2.setViewportView(jTable1);

        getContentPane().add(jScrollPane2);
        jScrollPane2.setBounds(46, 250, 315, 75);

        jLabel2.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        jLabel2.setText("Observação Criada pelo Professor");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(56, 223, 283, 17);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/agendaescolar/imagens/fundo2.png"))); // NOI18N
        jLabel3.setText("jLabel3");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(-30, -310, 920, 830);
        jLabel3.getAccessibleContext().setAccessibleName("");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formInternalFrameOpened(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameOpened
       DAOResponsavel objdaor= new DAOResponsavel();  
    //Buscar o id do responsavel para buscar seu alunos
    int idR=objdaor.ID;
         ArrayList<Aluno> lista = objdaor.retornarAlunos(idR);
         
                 
        if(jComboBoxAluno.getItemCount() > 0){
            jComboBoxAluno.removeAllItems();
        }
        
        lista.stream().forEach((meualuno) -> {
            jComboBoxAluno.addItem(meualuno.toString());
      }); 
   DAOAluno obj= new DAOAluno();
   //pegando o  aluno selecionado e salvado em uma variavel
    String nome=jComboBoxAluno.getSelectedItem().toString();
     
   //pegando o nome e retornando um id do Aluno
       idAluno=obj.retornarIdAluno(nome);
    //pegando o id do aluno e buscando a turma
       idturma=obj.retornaAlunoTurma(idAluno);
       montarAtividade();
       montarObservacao();
    
    }//GEN-LAST:event_formInternalFrameOpened

    private void jComboBoxAlunoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxAlunoActionPerformed
           
   DAOAluno obj= new DAOAluno();
   //pegando o  aluno selecionado e salvado em uma variavel
    String nome=jComboBoxAluno.getSelectedItem().toString();
   
      
   //pegando o nome e retornando um id do Aluno
       idAluno=obj.retornarIdAluno(nome);
    
    //pegando o id do aluno e buscando a turma
       idturma=obj.retornaAlunoTurma(idAluno);
        System.out.println(idturma);
      montarAtividade();
      montarObservacao();
    }//GEN-LAST:event_jComboBoxAlunoActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> jComboBoxAluno;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabelAluno;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTableAtividade;
    // End of variables declaration//GEN-END:variables
}
